# Generated by Django 6.0.4 on 2026-04-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('maestro', 'Excel Maestro'), ('factura', 'Factura PDF')], max_length=10)),
                ('archivo', models.FileField(upload_to='uploads/')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_normalizado', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('mes', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comparador_farmaceutico.archivo')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comparador_farmaceutico.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento_excel', models.CharField(blank=True, max_length=255)),
                ('medicamento_factura', models.CharField(blank=True, max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_maestro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_factura', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('OK', 'Precio correcto'), ('REVISAR', 'Revisar'), ('ERROR', 'Error / No coincide')], max_length=10)),
                ('score_match', models.FloatField(default=0)),
                ('coincidencia_nombre', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='comparador_farmaceutico.archivo')),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='comparador_farmaceutico.medicamento')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='comparador_farmaceutico.proceso')),
            ],
        ),
        migrations.AddField(
            model_name='archivo',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='comparador_farmaceutico.proceso'),
        ),
        migrations.CreateModel(
            name='ResumenProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_medicamentos', models.IntegerField(default=0)),
                ('coincidencias', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('por_revisar', models.IntegerField(default=0)),
                ('porcentaje_error', models.FloatField(default=0)),
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resumen', to='comparador_farmaceutico.proceso')),
            ],
        ),
    ]
